general: &general
  stripe:
    secret_key: 'sk_test_nWjL9fQH8v23uSiEPJT5d1Xs'
    publishable_key: 'pk_test_NxfJqAJ1j1w8p0K3959byw1P'
 
development: &development
  <<: *general
 
test: &test
  <<: *general
 
production: &production
  <<: *general