development:
  publishable_key: pk_test_51IFMYbLWZV2zSltnGxHBaSPrpaNUtXfaE83o3rsih86bfmHPpGW7D9OAc8gQGAIzuLwBAxrLYOPdSF4SsEPJnQbG00R5BUcDWp
  secret_key: sk_test_51IFMYbLWZV2zSltniAT01pxqJVY2IJ9UV7yT2WebwwsagC9wPLKu0uZb4rvefRmXYfAIxeB2PgFbrd3Br2moDx6H00m9zu2NZH